[[personal-details]]
= icon:user[] Detalhes Pessoais

.Paulo Jerônimo
****
Consultor, líder técnico de equipes, arquiteto e desenvonvedor de software, autor, instrutor e palestrante.

Desenvolvedor com preferência de uso para linguagens de programação e plataformas __open source__.
Atua no mercado corporativo desde 1993.
Produz soluções utilizando práticas ágeis.
Possui bastante experiência em arquitetura, desenvolvimento e infraestrutura para o atendimento a requisitos não funcionais em sistemas de missão crítica, escaláveis, tolerantes a falha e executáveis por cluster de servidores de aplicações em nuvens computacionais púbilicas ou privadas.

Também tem experiência em liderança de equipes autogerenciáveis que atuam em desafios de missão crítica.
Capaz de trabalhar efetivamente e de operar de forma independente mesmo em situações de pressão.
Hábil em influenciar e mentorar equipes de desenvolvimento para atender as necessidades estratégicas de negócio dos clientes.

Detém experiência na definição de estratégias empresariais, soluções arquiteturais, definição do modelo de uso, implantação e operação de processo de desenvolvimento ágil e ferramentas de arquitetura, design, planejamento e desenvolvimento de software incluindo processos de ALM e DevOps.

Possui forte atuação como consultor em ambientes envolvendo o uso de middlewares baseados em {JBossEAP}, {Wildfly}, {ApacheHTTP}, {ApacheTomcat}, {IBMWebSphere}, {OracleWebLogic}, e {GlassFish}.
Capaz de definir estratégias para instalação, otimização de tamanho e configuração, melhores práticas para administração, automação de implantação, desing de topologia, assim como práticas para resolução de problemas, análise e tuning de performance.

É instrutor em treinamentos corporativos e palestrante em eventos.
Possui mais de 3.400 horas de <<delivered-courses,treinamentos ministrados>> para vários clientes.
Os tópicos principais incluem arquitetura de software, Test Driven Development (TDD), desenvolvimento {JavaEE} (incluindo Web, Web Services, EJB, JPA, etc), e administração de servidores de middleware (JBoss, Oracle, WebSphere).
****

Contatos::
* icon:phone[] Fone/WhatsApp: {MyPhone}
* icon:skype[] Skype: {MyID}
webSites::
* http://paulojeronimo.com[paulojeronimo.com]
* {uri-ladoservidor}[ladoservidor.com] __([red]#não mais atualizado#)__
Mídias sociais::
* icon:linkedin[] Linkedin: {uri-paulojeronimo-linkedin} | icon:github[] GitHub: {uri-paulojeronimo-github} | icon:twitter[] Twitter: {uri-paulojeronimo-twitter} | icon:facebook[] Facebook: {uri-paulojeronimo-facebook} | icon:instagram[] Instagram: {uri-paulojeronimo-instagram}
icon:map-marker[]
Localização atual::
* {uri-paulojeronimo-location}[{MyLocation}]
