[personal-details]]
= icon:user[] Detalhes Pessoais

.Paulo Jerônimo
****
Consultor, líder técnico de equipes, arquiteto e desenvonvedor de software, autor, instrutor e palestrante.

Atua no mercado corporativo desde 1993.
Desenvolve dando preferência ao uso de plataformas e linguagens de programação __open source__.
Produz soluções utilizando práticas ágeis.
Experiente em definições arquiteturais, no desenvolvimento e na infraestrutura para o atendimento a requisitos não funcionais em sistemas de missão crítica, escaláveis, tolerantes a falha e executáveis por cluster de servidores de aplicações em nuvens computacionais púbilicas ou privadas.

Lidera equipes autogerenciáveis que atuam em desafios de missão crítica.
Trabalha efetivamente operando de forma independente mesmo em situações de pressão.
Influencia e mentora equipes de desenvolvimento para atender as necessidades estratégicas de negócio dos clientes.

Define estratégias empresariais, soluções arquiteturais, modelo de uso, implantação e operação de processo de desenvolvimento ágil.
Planeja o desenvolvimento software incluindo o uso de processos de {ALM} e {DevOps}.

Oferece consultoria em __cloud computing__ e servidores de aplicações.
Possui experiência prática no uso de plataformas como o {AWS} e o {Azure}.
Instala e configura plataformas como {OpenShift} e {CloudFoundry}.
Também, desde 2001, instala e configura de servidores de aplicações {Java}
(Ex.: {ApacheTomcat}, {JBossEAP}, {Wildfly}, {ApacheHTTP}, {ApacheTomcat}, {IBMWebSphere}, {OracleWebLogic}, {GlassFish}, etc).
É capaz de definir estratégias para instalação, otimização de tamanho e configuração, melhores práticas para administração, automação de implantação, desing de topologia, assim como práticas para resolução de problemas, análise e tuning de performance.

É instrutor em treinamentos corporativos e palestrante em eventos.
Possui mais de 3.400 horas de <<delivered-courses,treinamentos ministrados>> para vários clientes.
Os tópicos principais incluem arquitetura de software, Test Driven Development (TDD), desenvolvimento {JavaEE} (incluindo Web, Web Services, EJB, JPA, etc), e administração de servidores de middleware (JBoss, Oracle, WebSphere).
****

Contatos::
* icon:phone[] Fone/WhatsApp: {MyPhone}
* icon:skype[] Skype: {MyID}
webSites::
* http://paulojeronimo.com[paulojeronimo.com]
* {uri-ladoservidor}[ladoservidor.com] __([red]#não mais atualizado#)__
Mídias sociais::
* icon:linkedin[] Linkedin: {uri-paulojeronimo-linkedin} | icon:github[] GitHub: {uri-paulojeronimo-github} | icon:twitter[] Twitter: {uri-paulojeronimo-twitter} | icon:facebook[] Facebook: {uri-paulojeronimo-facebook} | icon:instagram[] Instagram: {uri-paulojeronimo-instagram}
icon:map-marker[]
Localização atual::
* {uri-paulojeronimo-location}[{MyLocation}]
