[[technical-skills]]
= icon:plug[] Technical Skills

*Currently using*:
_Virtualization, containers, cloud platforms and {DevOps}_: Microsoft
{Azure}, Amazon {AWS}, Google Cloud Platform ({GCP}), {OpenStack},
{Docker}, {Kubernetes}, {OpenShift}, {Git}, {GitLab}, {GitHub},
{BitBucket}, {Gradle}, {Nexus}, {Jenkins}, {TravisCI}, {Ansible},
{VMware}, {VirtualBox}, {KVM}, {Vagrant};
_Operational systems_: {macOS}, {Fedora}, {RHEL}, {CentOS}, {Ubuntu},
{ArchLinux};
_{Agile} Methodologies and practices_: {ExtremeProgramming}, {Scrum},
{Kanban}, {ContinuousIntegration};
[[programming-languages]] _Programming languages_: {Java}, {Groovy},
{Kotlin}, {JavaScript}, {TypeScript}, {Python}, {Ruby};
_Testing_: {TDD}, {BDD}, {IntegrationTesting}, {AcceptanceTesting},
{JUnit}, {JMock}, {Mockito}, {Arquillian}, {Cucumber}, {Selenium},
{Spek}, {Spock}, {Mocha}, {Chai}, {Jest};
_IDEs_: {IntelliJ}, {VisualStudioCode};
_Java development frameworks_: {JavaEE}, {Hibernate}, {Spring},
{SpringBoot};
_API development_: {Swagger}, {Postman}, {GraphQL};
_Web development_: {HTML}, {CSS}, {Sass}, {StyledComponents}, {NodeJS},
{npm}, {yarn}, {React}, {NextJS}, {Angular}, {Puppeteer}, {Python},
{Django}, {Jinja}, {WebSocket};
_Mobile development_: {Kotlin}, {ReactNative};
_Databases_: {Oracle}, {PostgreSQL}, {MongoDB};
_Documentation_: {UML}, {AsciiDoc}, {Asciidoctor_};
_Command line_: {Bash}, {sed}, {awk}, {curl}, {httpie}, {jq};
_{Blockchain} development_: {Ethereum}, {Solidity};
_Configuration languages_: {JSON}, {YAML}, {Dhall};
_Middleware and Big Data_: {ApacheTomcat}, {JBossEAP}, {WildFly},
{ApacheHTTP}, {Nginx}, {RabbitMQ}, {Kafka}, {ELKStack},
{ApacheNifi}, {SpringCloudDataFlow};
[[security]] _Security_: {OpenSSL}, {GnuPG}, {Passbolt},
{SpringSecurity}, {OAuth}, {OIDC}, {Keycloak};
_Tools_: {Vim}, {Tmux}, {Jira}, {SonarQube}; +
*Studying*:
{Vyper}, {Scala}, {Go}, {Haskell}, {Rust}; +
*Turning deprecating (using only to maintain existing
software if needed)*:
{XML}, {XSLT}, {Markdown}, Old versions of JBoss AS and {Tomcat},
{Struts}, {Ant}, {Maven}, {AngularJS}, {Subversion}, {NetBeans},
{Eclipse}, Windows, {Debian}, {Fedora}, C/{cpp}, {Pascal}, {Delphi}.
