[[technical-skills]]
= icon:plug[] Technical Skills

Studying and improving::
{Vyper}, {Go}, {Haskell}, {Rust}.

Currently using::
{VMware}, {VirtualBox}, {KVM}, {Vagrant}, {Docker}, {Kubernetes}, {Java}
8, {JavaEE}, {Kotlin}, {Groovy}, {AsciiDoc}, Asciidoctor, {Bash}, {sed},
{awk}, {curl}, {httpie}, {jq}, {Postman}, {Python}, {JavaScript},
{React}, {ReactNative}, {Angular}, {Ethereum}, {Solidity}, HTML 5, CSS
3, XML, {DevOps}, Continuous Integration, Test Driven Development (TDD),
Behavior Driven Development (BDD), Integration Testing, Acceptance
Testing, {JUnit}, {JMock}, {Mockito}, {Jest}, {Mocha}, {Chai},
{Arquillian}, {Cucumber}, {Selenium}, {Spek}, {Spock}, {JBossEAP} 6+,
{WildFly} 8+, {Keycloak}, {ApacheTomcat}, {ApacheHTTP}, {Nginx},
Microsoft {Azure}, Amazon {AWS}, Google Cloud Platform ({GCP}),
{OpenStack}, {OpenShift}, {Hibernate}, {Spring}, {SpringBoot}, {Vim},
{Tmux}, {Git}, {Gradle}, {NodeJS}, {npm}, {yarn}, {IntelliJ},
{VisualStudioCode}, {Jira}, {Jenkins}, {SonarQube}, {Nexus}, {macOS},
{Fedora}, {RHEL}, {CentOS}, {Ubuntu}, {ArchLinux}.

Trying to deprecated (and using only to maintain existing softwares if needed)::
{Markdown}, Old versions of JBoss AS and {Tomcat},
{Struts}, {Ant}, {Maven}, {AngularJS}, {Subversion}, {NetBeans}, {Eclipse}
Windows, {Debian}, {Fedora}, C/{cpp}, {Pascal}, {Delphi}.
