[[personal-details]]
= icon:user[] Personal Details

.Paulo Jerônimo
****
Consultant, developer, author, trainer, and speaker.
Develops in some programming languages (like {Java}, {Kotlin}, {Groovy},
{Bash}, {Python}, {JavaScript}, {Solidity} and {Vyper}) and using tools
running under open source or proprietary platforms.
Currently <<finishertech,developing some projects>> to run in the
{Ethereum} {BLockchain}.
Operating in the corporate market since 1993, produces solutions using
open source softwares and agile practices.
Has extensive experience in architecture, development, and
infrastructure to meet the non-functional software requirements in
mission critical, scalable, fault-tolerant, run by clusters of
application servers in public or private computing clouds.
Broad experience on leadership of high skilled teams and on mission
critical assignments, capable of working effectively under pressure and
able to operate independently.
Also, with an ability to influence and mentor the team and capable of
developing compelling business solutions to meet customers strategic
needs.

Vast experience on enterprise strategy definition, solution
architecture, usage model definition, deployment and rollout of agile
software development process and tools for architecture, design,
software planning, software development, ALM, and DevOps.

Strong actuation as a consultant on middleware environments based on
{JBossEAP}, {Wildfly}, {ApacheHTTP}, {ApacheTomcat}, {IBMWebSphere},
{OracleWebLogic}, and {GlassFish}.
Also, with experience in {Docker}, {Kubernetes}, {OpenShift},
{OpenStack}, {Keycloak}, {UAA} and {CloudFoundry}.
Capable to define strategy for installation, optimized sizing and
configuration, administration best practices, deployment automation,
topology design, and as a best practices mentor on troubleshooting,
performance analysis and performance tuning.

Experient trainer with more than 3,400 hours delivered in
<<delivered-courses,presential training classes>>
to many customers.
Main topics taught include Software Architecture, Test Driven
Development, {JavaEE} Development (including Web, Web Services, EJB,
JPA, etc), and JBoss Administration.
****

Contacts::
icon:phone[] Mobile Phone/WhatsApp: {MyPhone} | icon:skype[] Skype:
  {MyID}
WebSites::
Active: {MySite} |
https://finisher.tech/slides/projeto.A4.9slides.pdf[Finisher.Tech] +
Inactive: {uri-ladoservidor}[Lado Servidor]
Social Media::
icon:linkedin[] Linkedin: {uri-paulojeronimo-linkedin} | icon:github[]
  GitHub: {uri-paulojeronimo-github} | icon:twitter[] Twitter:
{uri-paulojeronimo-twitter} | icon:facebook[] Facebook:
{uri-paulojeronimo-facebook} | icon:instagram[] Instagram:
{uri-paulojeronimo-instagram} icon:youtube[] YouTube:
{uri-paulojeronimo-youtube}
icon:map-marker[] Location::
{uri-paulojeronimo-location}[{MyLocation}]
