[[technical-skills]]
= icon:plug[] Habilidades Técnicas

* Ferramentas Virtualização/ Contêineres: VMware, {VirtualBox}, {KVM}, {Vagrant}, {Docker}, {Swarm}, {Kubernetes}
* Linguagens e Especificações: {Kotlin}, {Solidity}, {Java} 8, {JavaEE} (BV, JPA, EJB, CDI, JMS, WebSocket, ...), {Groovy}, {AsciiDoc}, {Bash}, {Python}, {JavaScript}, HTML5, XML, CSS, {Markdown}, C/{cpp}, {Pascal}, {Asciidoc}
* Engenharia de Software: DevOps, Continuous Integration, Continuous Delivery, Unit Testing, Integration Testing
* Servidores de Aplicações: {JBossEAP} 6+, {WildFly} 8+, {ApacheTomcat}, {ApacheHTTP}, {Nginx}
* __Cloud Computing__: {AWS}, {Azure}, {CloudFoundry}, {OpenShift}
* Frameworks e Bibliotecas: {JUnit}, {Arquillian}, {Selenium}, {AngularJS}, Hibernate, {Spring}, {Struts}
* Ferramentas: {Vim}, {Tmux}, {Git}, {Gradle}, {NodeJS}, {Eclipse}, {IntelliJ}, JIRA, Asciidoctor, Dynatrace (APM), {Jenkins}, Sonar, {Nexus}, {Ant}, {Maven}, Subversion, {NetBeans}
* Sistemas Operacionais: {macOS}, Linux ({Fedora}, {RHEL}, {CentOS}, {Debian}, {Ubuntu}, {ArchLinux}), Windows
