[[technical-writing]]
= icon:book[] Escritos Técnicos

[[publications]]
== Livros, tutoriais, artigos

{published-jboss-domain-mode-scripts}/docs/pt-br/[Scripts para a automação de tarefas no JBoss EAP (em modo domain)]::
icon:calendar[] Agosto de 2017;
{published-jboss-domain-mode-scripts}/docs/pt-br/jboss-domain-mode-scripts.pdf[Versão em PDF].

{published-blockchain-demo}[Blockchain: Uma Visualização Gráfica]::
icon:calendar[] Julho de 2017;
{published-blockchain-demo}/blockchain-demo.pdf[Versão em PDF];
Código fonte: <<blockchain-demo>>.

{published-tutorial-metalsmith}[Tutorial de Metalsmith]::
icon:calendar[] Julho de 2016;
{published-tutorial-metalsmith}/index.pdf[Versão em PDF];
Código fonte: <<tutorial-metalsmith>>.

Praticando Git::
icon:calendar[] Março de 2016;
{published-praticando-git-livro}[Versão em PDF];
Código fonte: <<praticando-git-livro>>.

{published-tutorial-keycloak}[Tutorial de Keycloak]::
icon:calendar[] Setembro de 2015;
{published-tutorial-keycloak}/tutorial-keycloak.pdf[Versão em PDF];
Código fonte: <<tutorial-keycloak>>.

{published-javaee-tutorial-testes}[Testes em aplicações Java EE com Arquillian]::
icon:calendar[] Março de 2015;
{published-javaee-tutorial-testes}/javaee-tutorial-testes.pdf[Versão em PDF];
Código fonte: <<javaee-tutorial-testes>>.
